Module4 task1
htmlacademy-javascript/1571549-kekstagram-24 pull request #3
Opened 2021-10-03 15:27 UTC by Eprst-p

ДЗ по генерации объектов (25 фоток). Несколько корявая реализация сообщений в комментариях, и проверки на повтор (но по другому я пока не знаю). Консоль лог в конце пока оставил.

2021-10-04 07:20 UTC, craz3r requested changes
По функционалу задачи, все ок, но нужно поправить линтер, и поработать с названиями переменных.
Про то как лучше называть переменные и функции можно посмотреть в критериях. Все переменные, используемые в этом задании должны соответствовать критериям Б3-Б8

2021-10-04 16:45 UTC, Eprst-p commented
Добавил уникальность ID. Попробовал пофиксить имена переменных и конфликты линтера

2021-10-05 18:23 UTC, craz3r requested changes

2021-10-05 18:23 UTC, craz3r commented on js/main.js
> +const commentatorsNames = ['Ивашка', 'Наитемнейший', 'Броненосец', 'Серёга', 'Соловей', 'Мистер картофелина', 'Седовласый', 'Су-27', 'Водолаз', 'йцукен', 'Вася Пупыркин', 'Пёс', 'Кусок'
Первоначальный вариант именования был верный - это константный массив, должен записываться в верхнем регистре

2021-10-05 18:23 UTC, craz3r commented on js/main.js
> +const photoDescriptions = ['все раскуплено, говорили они', 'пляж на небе', 'корабль не видит меня', 'вид спереди', 'Пейн я ног не чувствую', 'драндулет', 'завтрак чемпиона', 'сушнячок'
здесь то же самое

2021-10-05 18:23 UTC, craz3r commented on js/main.js
> +const commentMessages = [
и здесь

2021-10-05 18:23 UTC, craz3r commented on js/main.js
> +      return usedIDies.some((uniqueID) => value === uniqueID);//
линтер продолжает ругаться, имя переменной в коллбэке дублирует имя переменной из внешнего окружения в строке 52

2021-10-05 18:23 UTC, craz3r commented on js/main.js
>  const createPhoto = function (i) {
думаю, достаточно назвать этот параметр index и линтер перестанет ругаться

2021-10-05 18:23 UTC, craz3r commented on js/main.js
>  for (let i = 0; i < 25; i++) {
здесь так же нужно выбрать более длинное имя переменной

2021-10-06 08:22 UTC, merged